apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-communicate
  name: demo-communicate
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: demo-communicate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-communicate
    spec:
      containers:
      - image: ${REPOSITORY_TAG} #CHANGE
        imagePullPolicy: IfNotPresent
        name: demo-communicate
        ports:
        - #name: liveness-port
          containerPort: 8101
#        env: //CHANGE
#          - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange
#        livenessProbe:
#          httpGet:
#            path: /healthcheck
#            port: 8100
#          initialDelaySeconds: 80
#          periodSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /healthcheck
#            port: 8100
#          initialDelaySeconds: 80
#          periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 20
      
---

apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: demo-communicate
  name: demo-communicate
  namespace: default
spec:
  ports:
  - nodePort: 30703
    port: 8101
    protocol: TCP
    #targetPort: 8100 
  selector:
    app: demo-communicate
  sessionAffinity: None 
  type: NodePort